apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: connectplus
  namespace: '135669823509'
  labels:
    cloud.googleapis.com/location: europe-west3
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 135669823509-compute@developer.gserviceaccount.com
      containers:
      - name: connectplus-1
        image: >-
          europe-west3-docker.pkg.dev/convrt-common/docker/connectplus@sha256:a2637827f95c8f406e3fa697975962c7247e503202cfd8ff09f14d64e226b5e6
        ports:
        - name: http1
          containerPort: 8000
        resources:
          limits:
            cpu: 8000m
            memory: 32Gi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8000
  traffic:
  - percent: 100
    latestRevision: true
