apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: connectplus-bg
  namespace: '135669823509'
  labels:
    cloud.googleapis.com/location: europe-west3
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/minScale: '0'
    run.googleapis.com/max-surge: '0'
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 135669823509-compute@developer.gserviceaccount.com
      containers:
      - name: connectplus-bg-1
        image: >-
          europe-west3-docker.pkg.dev/convrt-common/docker/connectplus-bg@sha256:b547a338f8975aac79a5978912446f7c7e0cb7bbed2d669c7f1e1fbb1a1d70ab
        ports:
        - name: http1
          containerPort: 80
        resources:
          limits:
            cpu: 4000m
            memory: 8Gi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 80
  traffic:
  - percent: 100
    latestRevision: true